In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as functional
import torch.optim as optim

In [3]:
torch.manual_seed(1)

In [4]:
x_train = torch.FloatTensor([[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]])
y_train = torch.FloatTensor([[0], [0], [0], [1], [1], [1]])

print(x_train)
print(y_train)

tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [12]:
W = torch.zeros(2, 1, requires_grad=True)   # zeros takes all non-keyword arguments as size parameter (in this case, size is 2 x 1)
b = torch.zeros(1, requires_grad=True)

In [13]:
print(W)
print(b)

tensor([[0.],
        [0.]], requires_grad=True)
tensor([0.], requires_grad=True)


In [14]:
optimizer = optim.SGD([W, b], lr=1)
nb_epochs = 100

for epoch in range(1, nb_epochs + 1):

    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = -(y_train * torch.log(hypothesis) + 
             (1 - y_train) * torch.log(1 - hypothesis)).mean()
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
        correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
        accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))

Epoch   10/100 Cost: 0.495571 Accuracy 66.67%
Epoch   20/100 Cost: 0.454665 Accuracy 66.67%
Epoch   30/100 Cost: 0.382432 Accuracy 83.33%
Epoch   40/100 Cost: 0.324347 Accuracy 83.33%
Epoch   50/100 Cost: 0.273294 Accuracy 83.33%
Epoch   60/100 Cost: 0.226980 Accuracy 100.00%
Epoch   70/100 Cost: 0.187111 Accuracy 100.00%
Epoch   80/100 Cost: 0.160040 Accuracy 100.00%
Epoch   90/100 Cost: 0.145725 Accuracy 100.00%
Epoch  100/100 Cost: 0.135644 Accuracy 100.00%


In [7]:
model = nn.Sequential(
   nn.Linear(2, 1), # input_dim = 2, output_dim = 1
   nn.Sigmoid() # 출력은 시그모이드 함수를 거친다
)
optimizer = optim.SGD(model.parameters(), lr=1)
nb_epochs = 100

for epoch in range(nb_epochs + 1):

    hypothesis = model(x_train)
    cost = functional.binary_cross_entropy(hypothesis, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
        correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
        accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))

Epoch    0/100 Cost: 0.614994 Accuracy 66.67%
Epoch   10/100 Cost: 0.747550 Accuracy 83.33%
Epoch   20/100 Cost: 0.633216 Accuracy 83.33%
Epoch   30/100 Cost: 0.538123 Accuracy 83.33%
Epoch   40/100 Cost: 0.450406 Accuracy 83.33%
Epoch   50/100 Cost: 0.366382 Accuracy 83.33%
Epoch   60/100 Cost: 0.287368 Accuracy 83.33%
Epoch   70/100 Cost: 0.219289 Accuracy 83.33%
Epoch   80/100 Cost: 0.173225 Accuracy 100.00%
Epoch   90/100 Cost: 0.151674 Accuracy 100.00%
Epoch  100/100 Cost: 0.140280 Accuracy 100.00%


In [8]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        return self.sigmoid(self.linear(x))

In [9]:
model = BinaryClassifier()
optimizer = optim.SGD(model.parameters(), lr=1)
nb_epochs = 100

for epoch in range(nb_epochs + 1):

    hypothesis = model(x_train)
    cost = functional.binary_cross_entropy(hypothesis, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5]) # 예측값이 0.5를 넘으면 True로 간주
        correct_prediction = prediction.float() == y_train # 실제값과 일치하는 경우만 True로 간주
        accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도를 계산
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format( # 각 에포크마다 정확도를 출력
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))

Epoch    0/100 Cost: 0.778947 Accuracy 33.33%
Epoch   10/100 Cost: 0.606802 Accuracy 66.67%
Epoch   20/100 Cost: 0.446548 Accuracy 66.67%
Epoch   30/100 Cost: 0.376169 Accuracy 83.33%
Epoch   40/100 Cost: 0.318945 Accuracy 83.33%
Epoch   50/100 Cost: 0.268428 Accuracy 83.33%
Epoch   60/100 Cost: 0.222594 Accuracy 100.00%
Epoch   70/100 Cost: 0.183695 Accuracy 100.00%
Epoch   80/100 Cost: 0.158160 Accuracy 100.00%
Epoch   90/100 Cost: 0.144616 Accuracy 100.00%
Epoch  100/100 Cost: 0.134716 Accuracy 100.00%
